# Generated by Django 3.2.3 on 2021-05-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=20)),
                ('banner_main', models.ImageField(upload_to='images/')),
                ('color', models.CharField(max_length=10)),
                ('millage', models.IntegerField()),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=10)),
                ('banner_image2', models.ImageField(upload_to='images/')),
                ('banner_image3', models.ImageField(upload_to='images/')),
                ('banner_image4', models.ImageField(upload_to='images/')),
                ('banner_image5', models.ImageField(upload_to='images/')),
                ('name_of_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auto.manufacturer')),
            ],
        ),
    ]
