# Generated by Django 3.2.3 on 2021-05-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0002_auto_20210517_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='banner_image2',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='banner_image3',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='banner_image4',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='banner_image5',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='banner_main',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
