# Generated by Django 3.2.3 on 2021-05-17 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0003_auto_20210517_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacture',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
